// Code generated by x/chardet/tools/gen_tld_data.go; DO NOT EDIT.
package chardet

type tldClass uint8

const (
	tldCentralWindows tldClass = iota
	tldCyrillic
	tldWestern
	tldGreek
	tldTurkishAzeri
	tldHebrew
	tldArabic
	tldBaltic
	tldVietnamese
	tldThai
	tldSimplified
	tldTraditional
	tldJapanese
	tldKorean
	tldSimplifiedTraditional
	tldTraditionalSimplified
	tldCentralIso
	tldIcelandicFaroese
	tldWesternCyrillic
	tldCentralCyrillic
	tldWesternArabic
	tldGeneric
	tldEu
)

var twoLetterTLDMap = map[string]tldClass{
	"ac": tldGeneric,
	"ae": tldArabic,
	"af": tldArabic,
	"ai": tldGeneric,
	"am": tldWesternCyrillic,
	"az": tldTurkishAzeri,
	"ba": tldCentralCyrillic,
	"bg": tldCyrillic,
	"bh": tldArabic,
	"by": tldCyrillic,
	"bz": tldGeneric,
	"cb": tldGeneric,
	"cc": tldGeneric,
	"cd": tldGeneric,
	"cn": tldSimplified,
	"cx": tldGeneric,
	"cy": tldGreek,
	"cz": tldCentralWindows,
	"dj": tldGeneric,
	"dz": tldArabic,
	"eg": tldArabic,
	"eu": tldEu,
	"fm": tldGeneric,
	"fo": tldIcelandicFaroese,
	"ge": tldWesternCyrillic,
	"gr": tldGreek,
	"hk": tldTraditionalSimplified,
	"hr": tldCentralWindows,
	"hu": tldCentralIso,
	"il": tldHebrew,
	"in": tldGeneric,
	"iq": tldArabic,
	"ir": tldArabic,
	"is": tldIcelandicFaroese,
	"jo": tldArabic,
	"jp": tldJapanese,
	"kg": tldCyrillic,
	"kp": tldKorean,
	"kr": tldKorean,
	"kw": tldArabic,
	"kz": tldCyrillic,
	"la": tldGeneric,
	"lb": tldArabic,
	"lt": tldBaltic,
	"lv": tldBaltic,
	"ly": tldArabic,
	"ma": tldArabic,
	"md": tldCyrillic,
	"me": tldGeneric,
	"mk": tldCyrillic,
	"mn": tldCyrillic,
	"mo": tldTraditionalSimplified,
	"mr": tldArabic,
	"ms": tldGeneric,
	"my": tldWesternArabic,
	"nu": tldGeneric,
	"om": tldArabic,
	"pk": tldArabic,
	"pl": tldCentralIso,
	"ps": tldArabic,
	"qa": tldArabic,
	"ro": tldCentralWindows,
	"rs": tldCyrillic,
	"ru": tldCyrillic,
	"sa": tldArabic,
	"sd": tldArabic,
	"sg": tldSimplifiedTraditional,
	"si": tldCentralIso,
	"sk": tldCentralWindows,
	"st": tldGeneric,
	"su": tldCyrillic,
	"sy": tldArabic,
	"th": tldThai,
	"tj": tldCyrillic,
	"tk": tldGeneric,
	"tm": tldCyrillic,
	"tn": tldArabic,
	"to": tldGeneric,
	"tr": tldTurkishAzeri,
	"tv": tldGeneric,
	"tw": tldTraditional,
	"ua": tldCyrillic,
	"uz": tldCyrillic,
	"vc": tldGeneric,
	"vn": tldVietnamese,
	"vu": tldGeneric,
	"ye": tldArabic,
}

var punycodeTLDMap = map[string]tldClass{
	"3e0b707e":           tldKorean,
	"54b7fta0cc":         tldWestern,
	"80ao21a":            tldCyrillic,
	"90a3ac":             tldCyrillic,
	"90ae":               tldCyrillic,
	"90ais":              tldCyrillic,
	"clchc0ea0b2g2a9gcd": tldSimplifiedTraditional,
	"d1alf":              tldCyrillic,
	"e1a4c":              tldEu,
	"fiqs8s":             tldSimplified,
	"fiqz9s":             tldSimplified,
	"fzc2c9e2c":          tldWestern,
	"j1amh":              tldCyrillic,
	"j6w193g":            tldTraditionalSimplified,
	"kprw13d":            tldTraditional,
	"kpry57d":            tldTraditional,
	"l1acc":              tldCyrillic,
	"lgbbat1ad8j":        tldArabic,
	"mgb2ddes":           tldArabic,
	"mgb9awbf":           tldArabic,
	"mgba3a4f16a":        tldArabic,
	"mgbaam7a8h":         tldArabic,
	"mgbah1a3hjkrd":      tldArabic,
	"mgbai9azgqp6j":      tldArabic,
	"mgbayh7gpa":         tldArabic,
	"mgbc0a9azcg":        tldArabic,
	"mgbcpq6gpa1a":       tldArabic,
	"mgberp4a5d4ar":      tldArabic,
	"mgbpl2fh":           tldArabic,
	"mgbtx2b":            tldArabic,
	"mgbx4cd0ab":         tldWesternArabic,
	"mix891f":            tldTraditionalSimplified,
	"node":               tldWesternCyrillic,
	"o3cw4h":             tldThai,
	"ogbpf8fl":           tldArabic,
	"p1ai":               tldCyrillic,
	"pgbs0dh":            tldArabic,
	"q7ce6a":             tldArabic,
	"qxa6a":              tldEu,
	"qxam":               tldGreek,
	"wgbh1c":             tldArabic,
	"wgbl6a":             tldArabic,
	"xkc2al3hye2a":       tldWestern,
	"y9a3aq":             tldWesternCyrillic,
	"yfro4i67o":          tldSimplifiedTraditional,
	"ygbi2ammx":          tldArabic,
}
