package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var arrStart = regexp.MustCompile(`^\s*(frequent_simplified|frequent_kanji|frequent_hangul):\s*\[`)
var hexRe = regexp.MustCompile(`0x[0-9A-Fa-f]+`)

func main() {
	root, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	in := filepath.Join(root, "chardetng", "src", "data.rs")
	out := filepath.Join(root, "x", "chardet", "cjk_data_gen.go")

	f, err := os.Open(in)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	vals := map[string][]string{}
	var cur string
	s := bufio.NewScanner(f)
	for s.Scan() {
		line := s.Text()
		if cur == "" {
			m := arrStart.FindStringSubmatch(line)
			if len(m) == 2 {
				cur = m[1]
				vals[cur] = []string{}
			}
			continue
		}
		if strings.Contains(line, "],") {
			cur = ""
			continue
		}
		h := hexRe.FindAllString(line, -1)
		vals[cur] = append(vals[cur], h...)
	}
	if err := s.Err(); err != nil {
		panic(err)
	}

	for _, k := range []string{"frequent_simplified", "frequent_kanji", "frequent_hangul"} {
		if len(vals[k]) == 0 {
			panic("missing " + k)
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by x/chardet/tools/gen_cjk_data.go; DO NOT EDIT.\n")
	b.WriteString("package chardet\n\n")
	writeArr := func(name, src string) {
		b.WriteString("var " + name + " = []rune{\n")
		for i, v := range vals[src] {
			if i%12 == 0 {
				b.WriteString("\t")
			}
			b.WriteString(v)
			b.WriteString(", ")
			if i%12 == 11 {
				b.WriteString("\n")
			}
		}
		if len(vals[src])%12 != 0 {
			b.WriteString(",\n")
		}
		b.WriteString("}\n\n")
	}
	writeArr("frequentSimplified", "frequent_simplified")
	writeArr("frequentKanji", "frequent_kanji")
	writeArr("frequentHangul", "frequent_hangul")
	b.WriteString("var frequentSimplifiedSet = toRuneSet(frequentSimplified)\n")
	b.WriteString("var frequentKanjiSet = toRuneSet(frequentKanji)\n")
	b.WriteString("var frequentHangulSet = toRuneSet(frequentHangul)\n")

	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Println("generated", out)
}
