package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var (
	reEnumStart = regexp.MustCompile(`^\s*pub enum Tld \{`)
	reEnumItem  = regexp.MustCompile(`^\s*([A-Za-z]+),\s*$`)
	reValStart  = regexp.MustCompile(`^\s*static TWO_LETTER_VALUES:`)
	reValItem   = regexp.MustCompile(`Tld::([A-Za-z]+)`)
	reKeyStart  = regexp.MustCompile(`^\s*static TWO_LETTER_KEYS:`)
	reKeyItem   = regexp.MustCompile(`\[b'([a-z])', b'([a-z])']`)
	rePunStart  = regexp.MustCompile(`^\s*static PUNYCODE_KEYS:`)
	rePunItem   = regexp.MustCompile(`b"([^"]+)"`)
)

func main() {
	root, _ := os.Getwd()
	in := filepath.Join(root, "chardetng", "src", "tld.rs")
	out := filepath.Join(root, "x", "chardet", "tld_data_gen.go")
	raw, err := os.ReadFile(in)
	if err != nil {
		panic(err)
	}
	lines := strings.Split(string(raw), "\n")

	enumNames := []string{}
	values := []string{}
	keys := []string{}
	punyKeys := []string{}
	punyValues := []string{}

	state := ""
	for _, ln := range lines {
		switch {
		case reEnumStart.MatchString(ln):
			state = "enum"
			continue
		case reValStart.MatchString(ln):
			state = "values"
			continue
		case reKeyStart.MatchString(ln):
			state = "keys"
			continue
		case rePunStart.MatchString(ln):
			state = "punykeys"
			continue
		}

		if state == "enum" {
			if strings.TrimSpace(ln) == "}" {
				state = ""
				continue
			}
			if m := reEnumItem.FindStringSubmatch(ln); len(m) == 2 {
				enumNames = append(enumNames, m[1])
			}
			continue
		}
		if state == "values" {
			if strings.Contains(ln, "];") {
				state = ""
				continue
			}
			if m := reValItem.FindStringSubmatch(ln); len(m) == 2 {
				values = append(values, m[1])
			}
			continue
		}
		if state == "keys" {
			if strings.Contains(ln, "];") {
				state = ""
				continue
			}
			if m := reKeyItem.FindStringSubmatch(ln); len(m) == 3 {
				keys = append(keys, m[1]+m[2])
			}
			continue
		}
		if state == "punykeys" {
			if strings.Contains(ln, "static PUNYCODE_VALUES") {
				state = "punyvals"
				continue
			}
			if m := rePunItem.FindStringSubmatch(ln); len(m) == 2 {
				punyKeys = append(punyKeys, m[1])
			}
			continue
		}
		if state == "punyvals" {
			if strings.Contains(ln, "];") {
				state = ""
				continue
			}
			if m := reValItem.FindStringSubmatch(ln); len(m) == 2 {
				punyValues = append(punyValues, m[1])
			}
		}
	}

	if len(values) != len(keys) {
		panic(fmt.Sprintf("two-letter key/value mismatch: %d %d", len(keys), len(values)))
	}
	if len(punyKeys) != len(punyValues) {
		panic(fmt.Sprintf("puny key/value mismatch: %d %d", len(punyKeys), len(punyValues)))
	}

	var b strings.Builder
	b.WriteString("// Code generated by x/chardet/tools/gen_tld_data.go; DO NOT EDIT.\n")
	b.WriteString("package chardet\n\n")

	b.WriteString("type tldClass uint8\n\n")
	b.WriteString("const (\n")
	for i, n := range enumNames {
		if i == 0 {
			b.WriteString("\ttld" + n + " tldClass = iota\n")
		} else {
			b.WriteString("\ttld" + n + "\n")
		}
	}
	b.WriteString(")\n\n")

	b.WriteString("var twoLetterTLDMap = map[string]tldClass{\n")
	for i, k := range keys {
		b.WriteString(fmt.Sprintf("\t%q: tld%s,\n", k, values[i]))
	}
	b.WriteString("}\n\n")

	b.WriteString("var punycodeTLDMap = map[string]tldClass{\n")
	for i, k := range punyKeys {
		b.WriteString(fmt.Sprintf("\t%q: tld%s,\n", strings.ToLower(k), punyValues[i]))
	}
	b.WriteString("}\n")

	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Println("generated", out)
}
